version: "3.3"

services:  

  mongodb:      
    build: ./mongodb
    image: mongodb
    container_name: mongodb    
    volumes:
      - ./../logs/mongobingo/data:/data/db
      - ./../logs/mongobingo/logs:/data/logs
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=Abcdf
      - MONGO_INITDB_ROOT_USERNAME=BingoBongo
    command: mongod
    networks:
      pubapi:
        aliases:
          - mongodb

  order:
    image: order
    build: ./order
    container_name: order
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    links:
      - mongodb     
    depends_on:     
      - mongodb             
    ports:
      - '9090:9090'    
    networks:
      - pubapi    


networks:
  pubapi:
    driver: bridge
